nice-digital/identity

- NICE.Identity.Authorisation.WebAPI/Models/Environments.cs
- NICE.Identity.Authorisation.WebAPI/Models/IdentityContext.cs
- NICE.Identity.Authorisation.WebAPI/Models/Roles.cs
- NICE.Identity.Authorisation.WebAPI/Models/Services.cs
- NICE.Identity.Authorisation.WebAPI/Models/UserRoles.cs
- NICE.Identity.Authorisation.WebAPI/Models/Users.cs
- NICE.Identity.Authorisation.WebAPI/Models/Websites.cs
https://nicedigital.atlassian.net/browse/IDAM-115
> IDAM-115 Implementing models from DB schema

- NICE.Identity.Authentication.Sdk/NICE.Identity.Authentication.Sdk.csproj
https://nicedigital.atlassian.net/browse/IDAM-105
> IDAM-105 Add SDK package metadata for NuGet creation

- NICE.Identity.Authorisation.WebAPI/appsettings.json
https://nicedigital.atlassian.net/browse/IDAM-107
> IDAM-107 Adding blank configuration for ELK, to be replaced by octo.

- .gitignore
- NICE.Identity.Authorisation.WebAPI/Startup.cs
https://nicedigital.atlassian.net/browse/IDAM-169
> IDAM-169 Enabling swagger in non-production environments

- NICE.Identity.Authorisation.WebAPI/appsettings.json
https://nicedigital.atlassian.net/browse/IDAM-184
> IDAM-184 Fixing kibana logging

- NICE.Identity.Authorisation.WebAPI/SeriLogger.cs
- NICE.Identity.Authorisation.WebAPI/appsettings.json
https://nicedigital.atlassian.net/browse/IDAM-184
> IDAM-184 Updating the kibana logging fix

- NICE.Identity.Authorisation.WebAPI/APIModels/Responses/UserInList.cs
https://nicedigital.atlassian.net/browse/IDAM-94
> IDAM-94 Adding more fields to the get user endpoint for test purposes

- NICE.Identity.Authorisation.WebAPI/APIModels/Requests/VerificationEmail.cs
- NICE.Identity.Authorisation.WebAPI/Configuration/AppSettings.cs
- NICE.Identity.Authorisation.WebAPI/Configuration/ManagementAPIConfig.cs
- NICE.Identity.Authorisation.WebAPI/Controllers/JobsController.cs
- NICE.Identity.Authorisation.WebAPI/NICE.Identity.Authorisation.WebAPI.csproj
- NICE.Identity.Authorisation.WebAPI/ProductionDependencies.cs
- NICE.Identity.Authorisation.WebAPI/Services/JobsService.cs
- NICE.Identity.Authorisation.WebAPI/Startup.cs
https://nicedigital.atlassian.net/browse/IDAM-39
> IDAM-39 Pending registration

- NICE.Identity.Authorisation.WebAPI/Controllers/UsersController.cs
- NICE.Identity.Authorisation.WebAPI/appsettings.json
https://nicedigital.atlassian.net/browse/IDAM-246
> IDAM-246 Synchronise DB With Rules 

- NICE.Identity.Authorisation.WebAPI/Controllers/JobsController.cs
https://nicedigital.atlassian.net/browse/IDAM-39
> IDAM-39 Resend activation email

- NICE.Identity.Authentication.Sdk/Extensions/ServiceCollectionExtensions.cs
https://nicedigital.atlassian.net/browse/IDAM-280
> IDAM-280 Change authorisation dependency injection

- NICE.Identity.Authorisation.WebAPI/APIModels/Requests/VerificationEmail.cs
- NICE.Identity.Authorisation.WebAPI/Controllers/JobsController.cs
- NICE.Identity.Authorisation.WebAPI/Services/JobsService.cs
- NICE.Identity.Authorisation.WebAPI/Startup.cs
https://nicedigital.atlassian.net/browse/IDAM-296
> IDAM-296 Add CORS configuration to IDAM API

- NICE.Identity.Authentication.Sdk/Extensions/ServiceCollectionExtensions.cs
- TestClients/NICE.Identity.TestClient.NETCore/Controllers/HomeController.cs
- TestClients/NICE.Identity.TestClient.NETCore/Models/UserViewModel.cs
- TestClients/NICE.Identity.TestClient.NETCore/Startup.cs
- TestClients/NICE.Identity.TestClient.NETCore/Views/Home/ApiData.cshtml
- TestClients/NICE.Identity.TestClient.NETCore/Views/Home/UserProfile.cshtml
- TestClients/NICE.Identity.TestClient.NETCore/Views/Shared/_Layout.cshtml
https://nicedigital.atlassian.net/browse/IDAM-285
> IDAM-285 Configure app to call Identity API

- NICE.Identity.Authorisation.WebAPI/Controllers/UsersController.cs
- NICE.Identity.Authorisation.WebAPI/DataModels/User.cs
https://nicedigital.atlassian.net/browse/IDAM-312
> IDAM-312 Fix lock user

- NICE.Identity.Authorisation.WebAPI/Controllers/UsersController.cs
- NICE.Identity.Authorisation.WebAPI/Services/UsersService.cs
- NICE.Identity.Test/Infrastructure/MockUserService.cs
- NICE.Identity.Test/UnitTests/Authorisation.WebAPI/Services/UserServiceTests.cs
https://nicedigital.atlassian.net/browse/IDAM-208
> IDAM-208 Search users

- NICE.Identity.Authorisation.WebAPI/APIModels/Environment.cs
- NICE.Identity.Authorisation.WebAPI/APIModels/Role.cs
- NICE.Identity.Authorisation.WebAPI/APIModels/Service.cs
- NICE.Identity.Authorisation.WebAPI/APIModels/UserRole.cs
- NICE.Identity.Authorisation.WebAPI/APIModels/VerificationEmail.cs
- NICE.Identity.Authorisation.WebAPI/APIModels/Website.cs
https://nicedigital.atlassian.net/browse/IDAM-329
> IDAM-329 DotNET Core 3.0 refactor attributes

- NICE.Identity.Authorisation.WebAPI/Controllers/UsersController.cs
- NICE.Identity.Authorisation.WebAPI/Services/UsersService.cs
- NICE.Identity.Authorisation.WebAPI/appsettings.json
https://nicedigital.atlassian.net/browse/IDAM-345
> IDAM-345 Unable to Delete User from API

- NICE.Identity.Authorisation.WebAPI/Repositories/Context.cs
- NICE.Identity.Test/UnitTests/Authorisation.WebAPI/Services/UserServiceTests.cs
https://nicedigital.atlassian.net/browse/EC-812
> EC-812 Prevent duplicates migrating users who have signed in already

- NICE.Identity.Authentication.Sdk/Extensions/ServiceCollectionExtensions.cs
https://nicedigital.atlassian.net/browse/IDAM-250
> IDAM-250 Enforcing secure cookies

- NICE.Identity.Authentication.Sdk/Extensions/ServiceCollectionExtensions.cs
https://nicedigital.atlassian.net/browse/IDAM-250
> IDAM-250 Making the secure cookie optional

- NICE.Identity.Authentication.Sdk/Configuration/AuthConfiguration.cs
https://nicedigital.atlassian.net/browse/IDAM-123
> IDAM-123 Enabling object initialisation syntax for auth configuration

- NICE.Identity.Authorisation.WebAPI/Services/UsersService.cs
- NICE.Identity.Test/UnitTests/Authorisation.WebAPI/Services/UserServiceTests.cs
https://nicedigital.atlassian.net/browse/IDAM-412.
> IDAM-412 Changing the sort order for the get users endpoint

- NICE.Identity.Authentication.Sdk/Extensions/ServiceCollectionExtensions.cs
- NICE.Identity.Authorisation.WebAPI/Configuration/EnvironmentConfig.cs
- NICE.Identity.Authorisation.WebAPI/Controllers/AdminController.cs
- NICE.Identity.Authorisation.WebAPI/DataModels/BasicUserInfo.cs
- NICE.Identity.Authorisation.WebAPI/DataModels/UserSync.cs
- NICE.Identity.Authorisation.WebAPI/HealthChecks/ApiKeyAuthenticationScheme.cs
- NICE.Identity.Authorisation.WebAPI/HealthChecks/DuplicateCheck.cs
- NICE.Identity.Authorisation.WebAPI/HealthChecks/UserSyncCheck.cs
- NICE.Identity.Authorisation.WebAPI/NICE.Identity.Authorisation.WebAPI.csproj
- NICE.Identity.Authorisation.WebAPI/Program.cs
- NICE.Identity.Authorisation.WebAPI/Services/Auth0ManagementService.cs
- NICE.Identity.Authorisation.WebAPI/Services/IProviderManagementService.cs
- NICE.Identity.Authorisation.WebAPI/Startup.cs
- NICE.Identity.Authorisation.WebAPI/appsettings.json
- NICE.Identity.Test/NICE.Identity.Test.csproj
https://nicedigital.atlassian.net/browse/STAK-18
> STAK-18 Health checks

- NICE.Identity.Authorisation.WebAPI/Controllers/UsersController.cs
- NICE.Identity.Authorisation.WebAPI/DataModels/UserSync.cs
- NICE.Identity.Authorisation.WebAPI/Exceptions.cs
- NICE.Identity.Authorisation.WebAPI/HealthChecks/UserSyncCheck.cs
- NICE.Identity.Authorisation.WebAPI/Repositories/Context.cs
- NICE.Identity.Authorisation.WebAPI/Services/UsersService.cs
- NICE.Identity.Test/UnitTests/Authorisation.WebAPI/Services/UserServiceTests.cs
https://nicedigital.atlassian.net/browse/IDAM-414
> IDAM-414 Duplicate email fix

- NICE.Identity.Authentication.Sdk/Authorisation/ApiTokenClient.cs
- NICE.Identity.Authentication.Sdk/Extensions/ServiceCollectionExtensions.cs
- NICE.Identity.Authentication.Sdk/NICE.Identity.Authentication.Sdk.csproj
- NICE.Identity.Authentication.Sdk/SessionStore/RedisOwinSessionStore .cs
- NICE.Identity.Authentication.Sdk/TokenStore/ApiTokenStore.cs
- NICE.Identity.Authentication.Sdk/TokenStore/RedisApiTokenStore.cs
- NICE.Identity.Test/IntegrationTests/Authentication.Sdk/TokenStore/ApiTokenStoreTests.cs
- NICE.Identity.Test/NICE.Identity.Test.csproj
- NICE.Identity.Test/UnitTests/Authentication.Sdk/Authorisation/ApiTokenClientTests.cs
- TestClients/NICE.Identity.TestClient.NETCore2.1/NICE.Identity.TestClient.NetCore2.1.csproj
- TestClients/NICE.Identity.TestClient.NETFramework4.5.2/packages.config
- TestClients/NICE.Identity.TestClient.NETFramework4.6.1/NICE.Identity.TestClient.NETFramework4.6.1.csproj
- TestClients/NICE.Identity.TestClient.NETFramework4.6.1/packages.config
- TestClients/NICE.Identity.TestClient.React/NICE.Identity.TestClient.React.csproj
https://nicedigital.atlassian.net/browse/ID-278
> ID-278 Indev integration

- NICE.Identity.Authentication.Sdk/Attributes/Http/AuthoriseAttribute.cs
- NICE.Identity.Authentication.Sdk/Attributes/Mvc/AuthoriseAttribute.cs
- NICE.Identity.Authentication.Sdk/Constants.cs
https://nicedigital.atlassian.net/browse/ID-278
> ID-278 Adding support to redirect to a permission denied route

- NICE.Identity.Authentication.Sdk/Authentication/AuthenticationService.cs
https://nicedigital.atlassian.net/browse/ID-310
> ID-310 Temporarily removing the refresh token revocation

- NICE.Identity.Authorisation.WebAPI/Controllers/OrganisationsController.cs
- NICE.Identity.Authorisation.WebAPI/Services/JobsService.cs
- NICE.Identity.Authorisation.WebAPI/Services/OrganisationRolesService.cs
- NICE.Identity.Authorisation.WebAPI/Services/OrganisationsService.cs
- NICE.Identity.Test/UnitTests/Authorisation.WebAPI/Services/JobsServiceTests.cs
- NICE.Identity.Test/UnitTests/Authorisation.WebAPI/Services/OrganisationRolesServiceTests.cs
- NICE.Identity.Test/UnitTests/Authorisation.WebAPI/Services/OrganisationsServiceTests.cs
https://nicedigital.atlassian.net/browse/IDAM-466 (delete org)
> IDAM-466 Delete Organisation
